delivery/urls.py
from us.views import (
    home_view,
    about_view,

)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('delivery/', include('us.urls', namespace='us')),
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

us/urls.py
from django.urls import path

from .views import (
    RegisterView,
    LoginView,
    logout_view,
    detail_view,
    international_view,
    domestic_view,
    forwarding_view,
    consultaion_view,
    household_view,
    commercial_view,
    air_freight_carrier_view,
    ocean_freight_view,
    road_view,
    soc_view,
    imp_view,
    implong_view,
    logistic_view,
    contact_view,
    detail_create_view,

)

app_name = 'us'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('detail-view/', detail_view, name='detail'),
    path('international-freight', international_view, name='international'),
    path('domestic-freight/', domestic_view, name='domestic'),
    path('freight-forwarding/', forwarding_view, name='forwarding'),
    path('freight-consultation/', consultaion_view, name='consultation'),
    path('household-goods/', household_view, name='household'),
    path('commercial-goods/', commercial_view, name='commercial'),
    path('air-freight-carrier/', air_freight_carrier_view, name='air-freight'),
    path('ocean-freight-forwarding/', ocean_freight_view, name='ocean-freight'),
    path('road-freight/', road_view, name='road-freight'),
    path('soc-movements/', soc_view, name='soc'),
    path('import-export/', imp_view, name='imp'),
    path('importers-logistic-reps/', implong_view, name='importers-rep'),
    path('logistic/', logistic_view, name='logistic'),
    path('contact/', contact_view, name='contact'),
    path('create/', detail_create_view, name='create'),

]

us/models.py
import random
import string
# Create your models here.
from builtins import ValueError

from PIL import Image
from django.contrib.auth.models import (
    AbstractBaseUser, BaseUserManager,
)
from django.db import models


# Create your models here.

class UserManager(BaseUserManager):
    def create_user(self, email, full_name, password=None, is_active=True, is_staff=False, is_admin=False):
        if not email:
            raise ValueError("Users must have an email address")
        if not password:
            raise ValueError("Users must have a password")
        if not full_name:
            raise ValueError("Users must have surname and other names")
        user_obj = self.model(
            email=self.normalize_email(email),
            full_name=full_name
        )
        user_obj.set_password(password)
        user_obj.staff = is_staff
        user_obj.active = is_active
        user_obj.admin = is_admin
        user_obj.save(using=self._db)
        return user_obj

    def create_staff_user(self, full_name, email, password=None):
        user = self.create_user(
            email,
            full_name,
            password=password,

            is_staff=True
        )
        return user

    def create_superuser(self, full_name, email, password=None):
        user = self.create_user(
            email,
            full_name,
            password=password,

            is_staff=True,
            is_admin=True
        )
        return user


class User(AbstractBaseUser):
    full_name = models.CharField(max_length=255, blank=True, null=True)
    email = models.EmailField(max_length=255, unique=True)
    active = models.BooleanField(default=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['full_name']

    objects = UserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.full_name

    def get_short_name(self):
        return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.staff

    @property
    def is_active(self):
        return self.active

    @property
    def is_admin(self):
        return self.admin


def generate_activationcode(size=12, chars=string.digits):
    ref_id = ''.join(random.choice(chars) for x in range(size))
    try:
        id_exist = User.objects.get(user_ref_id=ref_id)
        if id_exist.exits():
            generate_activationcode(size=8, chars=string.digits)
    except:
        return ''.join(random.choice(chars) for x in range(size))


class Detail(models.Model):
    ship_date = models.DateTimeField(auto_now_add=True)
    tracking_number = models.CharField(max_length=255, default=generate_activationcode, editable=False)
    delivery_date = models.DateTimeField()
    destination = models.CharField(max_length=255, )
    take_off_point = models.CharField(max_length=255, )
    sender_detail = models.CharField(max_length=255, )
    receiver_detail = models.CharField(max_length=255, )
    shipment_type = models.CharField(max_length=255, default='Travel Box')
    weight = models.CharField(max_length=255, default='20.kg')
    content = models.CharField(max_length=255, default='Family Treasure')
    quantity = models.IntegerField(default=1)
    sender_name = models.CharField(max_length=255, )
    receiver_name = models.CharField(max_length=255, )
    sender_country_flag = models.ImageField(upload_to='picture', max_length=255, null=True, blank=True)
    receiver_country_flag = models.ImageField(upload_to='picture', max_length=255, null=True, blank=True)
    service_type = models.CharField(max_length=255, default=' Express Delivery')
    status = models.CharField(max_length=255, default='Dispatched')
    pending = models.BooleanField(default=True)
    processed = models.BooleanField(default=False)

    def __str__(self):
        return self.tracking_number

    def save(self, *args, **kwargs):
        super(Detail, self).save(*args, **kwargs)
        mag = Image.open(self.sender_country_flag.path)
        imag = Image.open(self.receiver_country_flag.path)
        if imag.width > 50 or imag.height > 50 and mag.width > 50 or mag.height > 50:
            output_size = (50, 50)
            imag.thumbnail(output_size)
            mag.thumbnail(output_size)
            imag.save(self.receiver_country_flag.path)
            mag.save(self.sender_country_flag.path)


class Contact(models.Model):
    email = models.EmailField(max_length=255, unique=True)
    full_name = models.CharField(max_length=255, blank=True, null=True)
    phone_number = models.CharField(max_length=255)
    subject = models.CharField(max_length=255)
    message = models.TextField()
    pending = models.BooleanField(default=True)
    seen = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now_add=True, null=False)

    def __str__(self):
        return self.email

us/forms.py
from builtins import super

from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import Contact, Detail

User = get_user_model()


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'email',
            'full_name'
        )

    def clean_password(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super(RegisterForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserAdminChangeForm(forms.ModelForm):
    """a form for updating users. includes all the fields on the user, but replaces the password field with admin's password hash display """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'full_name', 'password', 'active', 'admin')

    def clean_password(self):
        return self.initial["password"]


class GuestForm(forms.Form):
    email = forms.EmailField()


class LoginForm(forms.Form):
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'placeholder': 'email@',
        'class': 'form-control'

    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'INSERT PASSWORD'
    }))


class DetailForm(forms.Form):
    tracking_number = forms.CharField(widget=forms.NumberInput(attrs={
        'placeholder': 'place your tacking number',
        'class': 'form-control'

    }))


class ContactForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={
        'rows': 3,
        'placeholder': 'Tell us your problems',
        'class': 'form-control'
    }))
    email = forms.EmailField(widget=forms.TextInput(attrs={
        'label': 'name',
        'placeholder': 'email@',
        'class': 'form-control'}))
    full_name = forms.CharField(widget=forms.TextInput(attrs={
        'label': 'name',
        'placeholder': 'FULL NAME',
        'class': 'form-control'}))
    subject = forms.CharField(widget=forms.TextInput(attrs={
        'label': 'subject',
        'placeholder': 'subject',
        'class': 'form-control'}))
    phone_number = forms.CharField(widget=forms.NumberInput(attrs={
        'placeholder': 'your phone number',
        'class': 'form-control'
    }))

    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'message', 'phone_number', 'subject']


class DetailCreateForm(forms.ModelForm):

    class Meta:
        model = Detail
        fields = [
            'delivery_date',
            'destination',
            'take_off_point',
            'sender_detail',
            'receiver_detail',
            'shipment_type',
            'weight',
            'content',
            'quantity',
            'sender_name',
            'receiver_name',
            'sender_country_flag',
            'receiver_country_flag',

        ]

us/views.py
import random
import string
from builtins import super

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from django.utils.http import is_safe_url
from django.views.generic import CreateView, FormView

from .forms import RegisterForm, LoginForm, DetailForm, ContactForm, DetailCreateForm
from .models import Detail


# Create your views here.


def create_ref_code():
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'register.html'
    success_url = '/us/login'


class LoginView(FormView):
    form_class = LoginForm
    template_name = '/login.html'

    def form_valid(self, form, *args, **kwargs):
        request = self.request
        next_ = request.GET.get('next')
        next_post = request.POST.get('next')
        redirect_path = next_ or next_post or None
        email = form.cleaned_data.get("email")
        password = form.cleaned_data.get("password")
        user = authenticate(request, username=email, password=password)
        if user is not None:
            login(request, user)
            try:
                del request.session['quest_email_id']
            except:
                pass
            if is_safe_url(redirect_path, request.get_host()):
                messages.info(self.request, 'put a valid email')
                return redirect(redirect_path)
            else:
                if request.user.is_admin or request.user.is_staff:
                    return redirect('/')
                else:
                    return redirect('/')
        return super(LoginView, self).form_invalid(form)


def logout_view(request):
    logout(request)
    return redirect('us:login')
    # Redirect to a success page.


def detail_view(request, *args, **kwargs):
    if request.method == "POST":
        searched = request.POST['tracking_number']
        tracking = Detail.objects.filter(tracking_number__iexact=searched)
        if tracking:
            context = {
                'searched': searched,
                'tracking': tracking
            }
            return render(request, "details.html", context)
        messages.warning(request, 'incorrect tracking number')
        return redirect("/")
    else:
        return redirect("/")


def home_view(request, *args, **kwargs):
    form = DetailForm()
    context = {
        'forms': form,
        'form': ContactForm
    }
    return render(request, "home.html", context)


def about_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "about.html", context)


def international_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "intfreit.html", context)


def domestic_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "domestic.html", context)


def forwarding_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "freightfarwd.html", context)


def consultaion_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "consultaion.html", context)


def household_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "household.html", context)


def commercial_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "commercial.html", context)


def air_freight_carrier_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "airfreight.html", context)


def ocean_freight_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "ocean.html", context)


def road_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "road.html", context)


def soc_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "soc.html", context)


def imp_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "imp.html", context)


def implong_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "importlong.html", context)


def logistic_view(request, *args, **kwargs):
    context = {
    }
    return render(request, "logistic.html", context)


def contact_view(request, *args, **kwargs):
    context = {
        'form': ContactForm
    }
    return render(request, "contact.html", context)


def contact_snippet_view(request, *args, **kwargs):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST or None)
        if form.is_valid():
            form.save()
            return redirect("/")
        form = ContactForm()
    context = {
        'form': form
    }
    return render(request, "contact.html", context)


def detail_create_view(request):
    form = DetailCreateForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        form = DetailCreateForm()
    context = {
        'form': form,
    }
    return render(request, 'detail-create.html', context)

us/templates/airfreight.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<body class="home header-transparent  header-sticky header-v1 hide-topbar-mobile"
      style="position: relative; min-height: 100%; top: 0px;">
<div id="page">
    {% include 'header.html' %}


    <div id="fh-header-minimized" class="fh-header-minimized fh-header-v1" style="height: 111px;"></div>

    <div class="page-header title-area">
        <div class="header-title">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 text-left">
                        <h1 class="page-title"> Air Freight Carrier</h1></div>
                </div>
            </div>
        </div>
        <div class="breadcrumb-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-12 col-xs-12 site-breadcrumb">
                        <nav class="breadcrumb">
                            <a class="home" href="./"><span>Home</span></a>
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                            <span>  Air Freight Carrier</span>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Page Header end-->
    <section class="partener-1 bluebg">
        <div class="container">
            <div class="fh-partner clearfix">
                <div class="list-item">


                    <div class="col-lg-12 col-md-12">


                    </div>


                </div>
            </div>
        </div>
    </section>
    <!--services Welcome sec -->
    <div class="service_dtl1 secpadd">
        <div class="container">
            <div class="row">
                <div class="col-md-12">


                    <div class="row paddsec">
                        <div class="col-md-8">
                            <div class="abotinforgt">
                                <div class="fh-section-title clearfix f25  text-left version-dark paddbtm40">
                                    <h2> Air Freight Carrier </h2>
                                </div>

                                <p>

                                    Domestic and International Air Freight service for any kind of goods enables the
                                    customer to ship anything in the process of relocating.
                                    We can meet all customer transportation needs around the world by our Air Freight
                                    Services.
                                    We bring customers shipments on time with safety to any destination in the world. We
                                    have no size, weight or schedule limitations and the customer can offer flexible
                                    options to and from all locations throughout the globe. We offer customers reliable,
                                    flexible and cost effective Air Freight shipping solutions.
                                </p>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="abotimglft">
                                <img src="images/garga.jpg" class="img-responsive">
                            </div>
                        </div>


                    </div>


                    <hr class="margtb40">


                    <div class="row paddsec">
                        <div class="col-md-12">
                            <div class="abotinforgt">
                                <div class="fh-section-title f20 clearfix  text-left version-dark paddbtm40">
                                    <h2>International Air Freight</h2>
                                </div>

                                <p>

                                    We service door to door service to major metropolitan areas around the world. When
                                    the customer needs some
                                    emergency international shipping, we offer some special service of Air freight
                                    solutions to deliver customer's
                                    goods via fastest possible way of shipping. First we understand customer's specific
                                    need and then we proceed our service
                                    to match customer's shipping requirements. We provide wide range of services to our
                                    customers and aim at
                                    increasing their productivity and profitability through our services.
                                </p>
                            </div>
                        </div>

                    </div>


                    <hr class="margbtm30">

                    <div class="fh-section-title f20 clearfix  text-left version-dark paddbtm40">
                        <h2>Domestic Air Freight</h2>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <p>
                                We understand the customer's need of domestic Air Freight services, and we are dedicated
                                to delivering goods on time to
                                meet customer's need. These services are provided by our well trained professionals,
                                they ensure to deliver these products
                                effectively and efficiently. We make sure that the cargo is delivered very safe via Air
                                Freight.
                                All the procedures are well executed right from the storage to customer's destination.
                            </p>
                        </div>


                    </div>


                    <hr class="margbtm30">


                    <div class="fh-section-title f20 clearfix  text-left version-dark paddbtm40">
                        <h2>Air Freight Forwarding Services</h2>


                        <div style="padding:20px 10px;">
                            <ul>
                                <li>Door to door delivery to worldwide destinations.</li>
                                <li>Well trained personnel for handling dangerous goods.</li>
                                <li>Pick up at origin</li>
                                <li>Customs Clearance</li>
                                <li>Cargo Insurance</li>
                            </ul>

                        </div>


                    </div>


                </div>
            </div>
        </div>
    </div>    <!--footer sec-->
    {% include 'footer.html' %}


    <div id="off-canvas-layer" class="off-canvas-layer"></div>
    <!--primary-mobile-nav end-->


    <!--Scroll to top-->
    <a id="scroll-top" class="backtotop" href="#page-top"><i class="fa fa-angle-up"></i></a>

    <!--Color switcher-->

    <!-- jquery Liabrary -->
</div>

</body>
{% endblock content %}

us/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<body class="home header-transparent  header-sticky header-v1 hide-topbar-mobile"
      style="position: relative; min-height: 100%; top: 0px;">
<div id="page">
    {% include 'header.html' %}


    <div id="fh-header-minimized" class="fh-header-minimized fh-header-v1" style="height: 111px;"></div>

    <div class="page-header title-area">
        <div class="header-title">
            <div class="container">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12 text-left">
                        <h1 class="page-title"> Contact</h1></div>
                </div>
            </div>
        </div>
        <div class="breadcrumb-area">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-sm-12 col-xs-12 site-breadcrumb">
                        <nav class="breadcrumb">
                            <a class="home" href="./"><span>Home</span></a>
                            <i class="fa fa-angle-right" aria-hidden="true"></i>
                            <span> Contact</span>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--Page Header end-->
    <section class="partener-1 bluebg">
        <div class="container">
            <div class="fh-partner clearfix">
                <div class="list-item">


                    <div class="col-lg-12 col-md-12">


                    </div>


                </div>
            </div>
        </div>
    </section>
    <!--services Welcome sec -->
    <section class="contactpagform graybg secpadd">
        <div class="container">
            <div class="fh-section-title clearfix f25 text-center version-dark paddbtm40">
                <h2>Leave Us A Message</h2>
            </div>
            <p class="paddbtm40 text-center">If you have any questions about the services we provide simply use the form
                below. We try and respond to all
                <br>queries and comments within 24 hours.</p>
            {% include 'snippet.html' %}

        </div>
    </section>    <!--footer sec-->
    {% include 'footer.html' %}


    <div id="off-canvas-layer" class="off-canvas-layer"></div>
    <!--primary-mobile-nav end-->


    <!--Scroll to top-->
    <a id="scroll-top" class="backtotop" href="#page-top"><i class="fa fa-angle-up"></i></a>

    <!--Color switcher-->

    <!-- jquery Liabrary -->
</div>

</body>
{% endblock content %}

us/templates/register.html
{% extends 'base.html' %}
{% load i18n %}

{% block head_title %}{% trans "Signup" %}{% endblock %}

{% block content %}
<div class="login-area area-padding fix">
    <div class="login-overlay"></div>
    <div class="table">
        <div class="table-cell">
            <div class="container">
                <div class="row">
                    <div class="col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-12">
                        <div class="login-form signup-form">
                            <h4 class="login-title text-center">REGISTER</h4>
                            <h4 class="login-title text-center" style="color: red;">US CITIZENS ONLY*</h4>
                            <div class="row">
                                <form id="contactForm" method="POST" action="{% url 'delivery:register' %}"
                                      class="log-form"> {% csrf_token %}
                                    <div class="col-md-12 col-sm-12 col-xs-12" id="div_id_full_name">
                                        <label for="id_full_name" class="control-label ">
                                            Full name
                                        </label>
                                        <input type="text" id="id_full_name" name="full_name" class="form-control"
                                               maxlength="255" placeholder="Username"
                                               required="">
                                    </div>
                                    <div class="col-md-12 col-sm-12 col-xs-12" id="div_id_email">
                                        <label for="id_email" class="control-label requiredField">
                                            Email<span class="asteriskField">*</span> </label>
                                        <input type="email" name="email"
                                               class="form-control" maxlength="255" required="" placeholder="email"
                                               id="id_email">
                                    </div>
                                    <div class="col-md-12 col-sm-12 col-xs-12" id="div_id_password1">
                                        <label for="id_password1" class="control-label requiredField">
                                            password<span class="asteriskField">*</span> </label>
                                        <input type="password" name="password1" id="id_password1" class="form-control"
                                               placeholder="Password" required="">
                                    </div>
                                    <div class="col-md-12 col-sm-12 col-xs-12" id="div_id_password2">
                                        <label for="id_password2" class="control-label requiredField">
                                            password confirmation<span class="asteriskField">*</span> </label>

                                        <input type="password" id="id_password2" name="password2" class="form-control"
                                               placeholder="Confirm Password" required="">
                                    </div>
                                    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                                        <div class="check-group flexbox">
                                            <label class="check-box">
                                                <input type="checkbox" class="check-box-input" checked>
                                                <span class="remember-text">I agree terms & conditions</span>
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                                        <button type="submit" id="submit" class="slide-btn login-btn">Signup</button>
                                        <div id="msgSubmit" class="h3 text-center hidden"></div>
                                        <div class="clearfix"></div>
                                    </div>
                                    <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                                        <div class="clear"></div>
                                        <div class="separetor text-center"><span>Or signup with</span></div>
                                        <div class="sign-icon">
                                            <ul>
                                                <li><a class="facebook" href="#"><i class="ti-facebook"></i></a></li>
                                                <li><a class="twitter" href="#"><i class="ti-twitter"></i></a></li>
                                                <li><a class="google" href="#"><i class="ti-google"></i></a></li>
                                            </ul>
                                            <div class="acc-not">have an account? <a
                                                    href="{% url 'delivery:login' %}">Login</a></div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}