delivery/urls.py
from us.views import (
    home_view,
    about_view,

)
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('delivery/', include('us.urls', namespace='us')),
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

us/urls.py
from django.urls import path

from .views import (
    RegisterView,
    LoginView,
    logout_view,
    detail_view,
    international_view,
    domestic_view,
    forwarding_view,
    consultaion_view,
    household_view,
    commercial_view,
    air_freight_carrier_view,
    ocean_freight_view,
    road_view,
    soc_view,
    imp_view,
    implong_view,
    logistic_view,
    contact_view,
    detail_create_view,

)

app_name = 'us'
urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', logout_view, name='logout'),
    path('detail-view/', detail_view, name='detail'),
    path('international-freight', international_view, name='international'),
    path('domestic-freight/', domestic_view, name='domestic'),
    path('freight-forwarding/', forwarding_view, name='forwarding'),
    path('freight-consultation/', consultaion_view, name='consultation'),
    path('household-goods/', household_view, name='household'),
    path('commercial-goods/', commercial_view, name='commercial'),
    path('air-freight-carrier/', air_freight_carrier_view, name='air-freight'),
    path('ocean-freight-forwarding/', ocean_freight_view, name='ocean-freight'),
    path('road-freight/', road_view, name='road-freight'),
    path('soc-movements/', soc_view, name='soc'),
    path('import-export/', imp_view, name='imp'),
    path('importers-logistic-reps/', implong_view, name='importers-rep'),
    path('logistic/', logistic_view, name='logistic'),
    path('contact/', contact_view, name='contact'),
    path('create/', detail_create_view, name='create'),

]

templates/about.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
{% include 'header.html' %}


<body class="home header-transparent  header-sticky header-v1 hide-topbar-mobile"


<div id="fh-header-minimized" class="fh-header-minimized fh-header-v1" style="height: 111px;"></div>
<!-- topbar end -->


<div class="page-header title-area">
    <div class="header-title">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <h1 class="page-title">About Us</h1>
                    <div class="hdrgtpara lftredbrdr">
                        <p>Our warehousing services are known nationwide to
                            be one of the most reliable, safe and affordable,
                            because we take pride in delivering the best of
                            warehousing services, at the most reasonable prices.</p>
                    </div>
                    <br>
                    <div class="desc" style="color: white">
                        <p>As a leader in global air freight forwarding,
                            DML Courier Servce excels in providing tailored
                            transportation</p>
                    </div>

                </div>
            </div>
        </div>
    </div>

</div>


<section class="aboutsec-2 secpaddbig">
    <div class="container">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="abotinforgt">
                    <div class="fh-section-title clearfix  text-left version-dark paddbtm30">
                        <h2>Who We are</h2>
                    </div>
                    <p>
                        DML Courier Servce' unique position allows us to offer full truckload (FTL) as well as less than
                        truckload (LTL) service through our vast network of third party providers. We take pride in our
                        ability to provide timely and reliable service, with our promise of satisfaction delivered with
                        each shipment we move.
                    </p>


                    <p>
                        We offer a range of expertise aimed at helping customers re-engineer and re-invent their
                        businesses to compete successfully in an ever-changing marketplace,
                        with the final objective of safely and promptly delivering all our customers consignments as
                        expected.


                        We strongly believe that pursuing all of these goals is in our interest and in the interest
                        of all of our stakeholders
                        are customers, employees, investors and the planet as a whole. We add value to cargo
                        people’s interaction with us, with excellent services or products.

                    </p>


                    <p>

                        DML Courier Servce' unique position allows us to offer full truckload (FTL) as well as less
                        than truckload (LTL)
                        service through our vast network of third party providers. We take pride in our ability to
                        provide timely and reliable service,
                        with our promise of satisfaction delivered with each shipment we move.
                    </p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--About us end-->

<!-- Feature sec -->
<section class="features-3 bluebg">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="fh-feature-box "><span class="chars">M</span>
                    <h4 class="box-title">Our Mission</h4>
                    <div class="desc">We meet our customers’ demands for a personal &amp; profesional service by
                        offering innovative supply chain solutions.
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="fh-feature-box "><span class="chars">V</span>
                    <h4 class="box-title">Our Vision</h4>
                    <div class="desc">We proactively and constantly look for new possibilities. Therefore, an
                        important part of our vision is to attract &amp; retain.
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="fh-feature-box "><span class="chars">C</span>
                    <h4 class="box-title">Core Values</h4>
                    <div class="desc">Procedures, values and attitudes are crucial to our reputation – not to
                        mention the success we enjoy.
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Feature sec end -->

<!-- featured sec -->
<section class="whychoos-3 secpadd">
    <div class="container">
        <div class="fh-section-title clearfix text-left version-dark paddbtm30">
            <h2>Our Services</h2>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <div class="fh-icon-box  style-2 version-dark">
                    <div class="desc">
                        <p>

                            Our services include armored car transportation, money processing, long-distance
                            transport of valuables, vaulting and other value-added solutions. DML Courier Servce
                            specializes in the secure transportation and handling of valuable goods throughout the
                            logistics value chain, from raw materials and components to finished products within the
                            mining, bank note, precious metals, jewelry, security, art and pharmaceutical
                            industries.

                            DML Courier Servce provides such value added services as Customs Clearance and
                            Brokerage, Inventory Management, Trade Show Services, Cash Processing, Walk-in Service
                            Centers, Free Trade Zones and Bonded Warehouses.
                        </p>


                    </div>
                </div>
            </div>
        </div>
    </div>
</section>


{% include 'footer.html' %}



<!--Scroll to top-->
<a id="scroll-top" class="backtotop" href="#page-top"><i class="fa fa-angle-up"></i></a>

<!--Color switcher-->


{% endblock %}

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head_title %}{% endblock %}
    {% block extra_head %}
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta name="keywords"
          content="DML Courier Servce and Courier Services, Logistics, mailroom , warehousing , best courier service worlwide, global logistics company, ecommerce delivery, ecommerce courier service ,local shipment, international shipment, same day delivery , logistics support, Amazon delivery, delivery services, delivery service for ecommerce, ecommerce delivery in Globally , deal dey delivery, Global logistics company">

    <meta name="description"
          content="DML Courier Servce is a leading logistics and distribution services company established in 2009. We offer a wide array of express courier and logistic support solutions to our various customers">
    <meta content="IE=edge" http-equiv="X-UA-Compatible">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <meta http-equiv="ImageToolbar" content="No"/>
    <meta http-equiv="content-language" content="en-US"/>
    <meta name="title" content="DML Courier Servce | Express Delivery, Courier &amp; Shipping Services | Worlwide"/>

    <meta property="og:type" content="Logistics and Courier Services"/>
    <meta property="og:title"
          content="DML Courier Servce | Express Delivery, Courier &amp; Shipping Services | Worlwide"/>
    <meta property="og:description"
          content="DML Courier Servce is a leading logistics and distribution services company established in 2009. We offer a wide array of express courier and logistic support solutions to our various customers">
    <meta name="keywords">
    <meta property="og:site_name" content="DML Courier Servce"/>
    <meta property="og:url" content="{% url 'home' %}"/>
    <meta property="og:image" content="{% static 'static/img/logo.png' %}"/>


    <title>DML Courier Servce | Express Delivery, Courier &amp; Shipping Services | Worlwide</title>
    <!-- Stylesheets -->
    <!-- bootstrap v3.3.6 css -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">

    <!-- font-awesome css -->
    <link href="{% static 'css/font-awesome.css' %}" rel="stylesheet">
    <!-- flaticon css -->
    <link href="{% static 'css/flaticon.css' %}" rel="stylesheet">
    <!-- factoryplus-icons css -->
    <link href="{% static 'css/factoryplus-icons.css' %}" rel="stylesheet">
    <!-- animate css -->
    <link href="{% static 'css/animate.css' %}" rel="stylesheet">
    <!-- owl.carousel css -->
    <link href="{% static 'css/owl.css' %}" rel="stylesheet">
    <!-- fancybox css -->
    <link href="{% static 'css/jquery.fancybox.css' %}" rel="stylesheet">
    <link href="{% static 'css/hover.css' %}" rel="stylesheet">
    <link href="{% static 'css/frontend.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">

    <!-- switcher css -->
    <link href="{% static 'vcss/switcher.css' %}" rel="stylesheet">
    <link rel='stylesheet' id='factoryhub-color-switcher-css' href="{% static 'css/switcher/default.css' %}"/>
    <!-- revolution slider css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/revolution/settings.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/revolution/layers.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/revolution/navigation.css' %}">

    <!--Favicon-->
    <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
    <!-- Responsive -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <!-- bootstrap v3.3.6 js -->
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <!-- fancybox js -->
    <script src="{% static 'js/bootstrap.min.js' %}js/jquery.fancybox.pack.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}js/jquery.fancybox-media.js"></script>
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
    <!-- owl.carousel js -->
    <script src="{% static 'js/bootstrap.min.js' %}js/owl.js"></script>
    <!-- counter js -->
    <script src="{% static 'js/jquery.appear.js' %}"></script>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css"
          integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>
    <!-- validate js -->
    <!-- switcher js -->

    <!-- REVOLUTION JS FILES -->
    <script type="text/javascript" src="{% static 'js/revolution/jquery.themepunch.tools.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/revolution/jquery.themepunch.revolution.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/revolution/extensions/revolution.extension.actions.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/revolution/extensions/revolution.extension.carouseil.mn.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/revolution/extensions/revolution.extension.kenburn.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/revolution/extensions/revolution.extension.layeranimation.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/revolution/extensions/revolution.extension.migration.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/revolution/extensions/revolution.extension.navigation.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/revolution/extensions/revolution.extension.parallax.min.js' %}"></script>
    <script type="text/javascript"
            src="{% static 'js/revolution/extensions/revolution.extension.slideanims.min.js' %}"></script>

    <!-- script JS  -->
    <script src="{% static 'js/scripts.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>


    <script src="{% static 'js/jquery.bpopups2.min.js' %}"></script>

    {% endblock %}


</head>
<body>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }}" role="alert">
    {{ message }}
</div>
{% endfor %}
{% endif %}

{% block content %}
replace me
{% endblock %}

{% block extra_body %}
{% endblock %}


</body>
<footer>
    {% block footer %}


    {% endblock footer %}

</footer>

</html>

templates/footer.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="footer-widgets widgets-area">
    <div class="contact-widget">
        <div class="container">
            <div class="row">
                <div class="contact col-md-3 col-xs-12 col-sm-12">
                    <a href="#" class="footer-logo"><img src="{% static 'img/logo-light.png' %}" alt="Footer Logo"></a>
                </div>
                <div class="contact col-md-3 col-xs-12 col-sm-12"><i class="flaticon-signs"></i>
                    <p>Address :</p>
                    <h4>11101 Santa Monica Blvd, Los Angeles, CA 90025</h4></div>
                <div class="contact col-md-3 col-xs-12 col-sm-12"><i class="flaticon-phone-call "></i>
                    <p>Phone Number :</p>
                    <h4>+1(910) 2273899</h4>
                </div>
                <div class="contact col-md-3 col-xs-12 col-sm-12"><i class="flaticon-clock-1"></i>
                    <p>Opening Hours :</p>
                    <h4>MON - FRI: 8AM - 5PM</h4></div>
            </div>
        </div>
    </div>
    <div class="footer-sidebars">
        <div class="container">
            <div class="row">
                <div class="footer-sidebar footer-1 col-xs-12 col-sm-6 col-md-3">
                    <div class="widget widget_text">
                        <h4 class="widget-title">About Cargo</h4>
                        <div class="textwidget">
                            <p>DML Courier Servce Services is a global
                                supplier of transport and logistics
                                solutions.</p>
                        </div>
                    </div>
                    <!--<div class="widget cargohub-social-links-widget">
                        <div class="list-social style-1">
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-facebook"></i></a>
                            <a href="#" target="_blank"><i class="fa fa-twitter"></i></a>
                        </div>
                    </div> -->
                </div>
                <div class="footer-sidebar footer-2 col-xs-12 col-sm-6 col-md-3">
                    <div class="widget widget_nav_menu">
                        <h4 class="widget-title">Useful Links</h4>
                        <div class="menu-service-menu-container">
                            <ul class="menu">
                                <li><a href="{% url 'home' %}"> Home</a></li>
                                <li><a href="{% url 'about' %}"> About Us</a></li>
                                <li><a href="{% url 'us:logistic' %}">Logistics</a></li>
                                <li><a href="{% url 'us:contact' %}">Contact</a></li>

                            </ul>
                        </div>
                    </div>
                </div>

                <div class="footer-sidebar footer-2 col-xs-12 col-sm-6 col-md-3">
                    <div class="widget widget_nav_menu">
                        <h4 class="widget-title">Services</h4>
                        <div class="menu-service-menu-container">
                            <ul class="menu">
                                <li><a href="{% url 'us:international' %}">International Freight</a></li>
                                <li><a href="{% url 'us:domestic' %}">Domestic Freight</a></li>
                                <li><a href="{% url 'us:forwarding' %}">Freight Forwarding</a></li>
                                <li><a href="{% url 'us:consultation' %}">Consultation</a></li>
                            </ul>
                        </div>
                    </div>
                </div>


                <div class="footer-sidebar footer-2 col-xs-12 col-sm-6 col-md-3">
                    <div class="widget widget_nav_menu">
                        <h4 class="widget-title">Freight</h4>
                        <div class="menu-service-menu-container">
                            <ul class="menu">
                                <li><a href="{% url 'us:air-freight' %}">Air Freight Carrier</a></li>
                                <li><a href="{% url 'us:ocean-freight' %}">Ocean Freight Forwarding</a></li>
                                <li><a href="{% url 'us:road-freight' %}">Road Freight Forwarding</a></li>
                                <li><a href="{% url 'us:soc' %}">SOC Movements</a></li>
                            </ul>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>

<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="footer-copyright col-md-12 col-sm-12 col-sx-12">
                <div class="site-info" style="text-align:center;">Copyright @ 2021 DML Courier Servce. All Right
                    Reserved
                </div>
            </div>

        </div>
    </div>
</footer>

{% endblock %}

templates/header.html
{% extends 'base.html' %}

{% load static %}

{% block content %}


<div>
    <div>
        <header id="masthead" class="site-header clearfix minimized" style="top: 60px;">

            <div class="header-main clearfix">
                <div class="container mobile_relative">
                    <div class="row">
                        <div class="site-logo col-md-3 col-sm-6 col-xs-6">
                            <a href="./" class="logo">
                                <img src="{% static 'images/logo.png' %}" alt="DML Courier Servce"
                                     class="logo-light show-logo">
                                <img src="{% static 'images/logo.png' %}" alt="DML Courier Servce"
                                     class="logo-dark hide-logo">
                            </a>
                            <h1 class="site-title"><a href="./">DML Courier Servce</a></h1>
                            <h2 class="site-description">Global Logistics Services</h2>
                        </div>
                        <div class="site-menu col-md-9 col-sm-6 col-xs-6">
                            <nav id="site-navigation" class="main-nav primary-nav nav">
                                <ul class="menu">
                                    <li><a href="{% url 'home' %}"> Home</a></li>
                                    <li><a href="{% url 'about' %}"> About Us</a></li>

                                    <li class="has-children"><a href="javascript:void(0)" class="dropdown-toggle">
                                        Services</a>
                                        <ul class="sub-menu">
                                            <li><a href="{% url 'us:international' %}">International Freight</a></li>
                                            <li><a href="{% url 'us:domestic' %}">Domestic Freight</a></li>
                                            <li><a href="{% url 'us:forwarding' %}">Freight Forwarding</a></li>
                                            <li><a href="{% url 'us:consultation' %}">Consultation</a></li>
                                        </ul>
                                    </li>


                                    <li class="has-children"><a href="javascript:void(0)"
                                                                class="dropdown-toggle">Movers</a>
                                        <ul class="sub-menu">
                                            <li><a href="{% url 'us:household' %}">Household Goods</a></li>
                                            <li><a href="{% url 'us:commercial' %}">Commercial Goods</a></li>
                                        </ul>
                                    </li>


                                    <li class="has-children"><a href="javascript:void(0)"
                                                                class="dropdown-toggle">Freight</a>
                                        <ul class="sub-menu">
                                            <li><a href="{% url 'us:air-freight' %}">Air Freight Carrier</a></li>
                                            <li><a href="{% url 'us:ocean-freight' %}">Ocean Freight Forwarding</a></li>
                                            <li><a href="{% url 'us:road-freight' %}">Road Freight Forwarding</a></li>
                                            <li><a href="{% url 'us:soc' %}">SOC Movements</a></li>
                                        </ul>
                                    </li>


                                    <li class="has-children"><a href="javascript:void(0)"
                                                                class="dropdown-toggle">Customs</a>
                                        <ul class="sub-menu">
                                            <li><a href="{% url 'us:imp' %}">Export - Import</a></li>
                                            <li><a href="{% url 'us:importers-rep' %}">Importer's Rep</a></li>
                                        </ul>
                                    </li>

                                    <li><a href="{% url 'us:logistic' %}">Logistics</a></li>

                                    <li><a href="{% url 'us:contact' %}">Contact</a></li>
                                    <li class="extra-menu-item menu-item-button-link">
                                        <div class="widget cargo-search-widget">

                                        </div>

                                    </li>
                                </ul>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>


        </header>

    </div>
</div>

{% endblock %}

templates/snippet.html
{% extends 'base.html' %}

{% block content %}

<form class="form-group" method="post" id="contactForm" name="contactForm"
      action="{% url 'us:contact' %}">{% csrf_token %}
    <div class="fh-form fh-form-3">
        <div class="row">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <p class="field">
                    <label for="email" style="color:red">Email <span>*</span></label>

                    {{ form.full_name }}

                </p>
                <p class="field">
                    <label for="email" style="color:red">Email <span>*</span></label>

                    {{ form.email }}
                </p>
                <p class="field">
                    <label for="subject" style="color:red">subject <span>*</span></label>

                    {{ form.subject }}

                </p>
                <p class="field">
                    <label for="phone_number" style="color:red">phone number <span>*</span></label>

                    {{ form.phone_number }}

                </p>
            </div>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <p class="field single-field">
                    <label for="message" style="color:red">message <span>*</span></label>

                    {{ form.message }}
                </p>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <p class="field submit">

                    <button class="fh-btn" name="sendMessage" id="sendMessage" type="submit">Send Message
                    </button>


                </p>
            </div>
        </div>
    </div>
</form>
{% endblock content %}